name: CI

# This workflow run tests and build for each push

on:
  push:
    branches:
      - main

jobs:

  Build contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly
          set -e

      - name: Build
        run: |
          cd contract     
          rustup target add wasm32-unknown-unknown
          cargo build --target wasm32-unknown-unknown --release
          cp target/wasm32-unknown-unknown/release/*.wasm ./res/
      
      - uses: actions/upload-artifact@v3
        with:
          name: crossword.wasm
          path: ./contract/res/crossword.wasm